### ISSUE TITLE
fatal error: gst/gst.h

### ISSUE THREAD

**Issue by superseed77** [dasaki/ofxKinectBlobTracker#1]
I try to compile the example on ubuntu 13.10 OF 0.8.0 an I got this  message
In file included from ../../../libs/openFrameworks/video/ofGstVideoGrabber.h:3:0,
                 from ../../../libs/openFrameworks/video/ofVideoGrabber.h:31,
                 from ../../../libs/openFrameworks/ofMain.h:76,
                 from src/testApp.h:3,
                 from src/main.cpp:1:
../../../libs/openFrameworks/video/ofGstUtils.h:13:21: fatal error: gst/gst.h: Aucun fichier ou dossier de ce type
 #include <gst/gst.h>

all dependecies are installed 

any help ?

**Comment by dasaki** [comment]
Hi,

I've just compiled ofxKinectBlobTracker on Ubuntu 12.04 64 and oF
0.8.1 without problems.

Googling for "../../../libs/openFrameworks/video/ofGstUtils.h:13:21:
fatal error: gst/gst.h" gives these issues that may point you out to a
solution:

https://github.com/ofTheo/ofxKinect/issues/130
https://github.com/openframeworks/openFrameworks/issues/2625

Also, here is the list of dependencies shown by ldd on the compiled executable:

linux-vdso.so.1 =>  (0x00007fff197cf000)
    libusb-1.0.so.0 => /usr/local/lib/libusb-1.0.so.0 (0x00007f3392c37000)
    libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f3392a20000)
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f3392817000)
    libsndfile.so.1 => /usr/lib/x86_64-linux-gnu/libsndfile.so.1
(0x00007f33925b0000)
    libopenal.so.1 => /usr/lib/x86_64-linux-gnu/libopenal.so.1 (0x00007f3392360000)
    libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f3392101000)
    libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
(0x00007f3391d26000)
    libGLU.so.1 => /usr/lib/x86_64-linux-gnu/libGLU.so.1 (0x00007f3391ab8000)
    libGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 (0x00007f3391851000)
    libGLEW.so.1.6 => /usr/lib/x86_64-linux-gnu/libGLEW.so.1.6 (0x00007f33915e6000)
    libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007f3391328000)
    libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6
(0x00007f339108b000)
    libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1
(0x00007f3390e55000)
    libmpg123.so.0 => /usr/lib/x86_64-linux-gnu/libmpg123.so.0 (0x00007f3390bfb000)
    libglut.so.3 => /usr/lib/libglut.so.3 (0x00007f33909b2000)
    libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f339067d000)
    libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007f3390475000)
    libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1
(0x00007f339026f000)
    libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f339005f000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f338fe42000)
    libfreeimage.so.3 => /usr/lib/libfreeimage.so.3 (0x00007f338fb48000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f338f844000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f338f548000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f338f331000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f338ef71000)
    libFLAC.so.8 => /usr/lib/x86_64-linux-gnu/libFLAC.so.8 (0x00007f338ed27000)
    libvorbisenc.so.2 => /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2
(0x00007f338e857000)
    libvorbis.so.0 => /usr/lib/x86_64-linux-gnu/libvorbis.so.0 (0x00007f338e62b000)
    libogg.so.0 => /usr/lib/x86_64-linux-gnu/libogg.so.0 (0x00007f338e424000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f338e21f000)
    libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007f338dffa000)
    libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f338dde9000)
    libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1
(0x00007f338dbe5000)
    libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f338d9df000)
    libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1
(0x00007f338d7dd000)
    libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0
(0x00007f338d5c5000)
    libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f338d3a7000)
    libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f338d19c000)
    libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0
(0x00007f338cf04000)
    libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f338ccdc000)
    libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0
(0x00007f338cad9000)
    libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0
(0x00007f338c8ce000)
    libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1
(0x00007f338c6c4000)
    libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f338c49a000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f3392e78000)
    libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f338c249000)
    libmng.so.1 => /usr/lib/x86_64-linux-gnu/libmng.so.1 (0x00007f338bfc1000)
    libopenjpeg.so.2 => /usr/lib/libopenjpeg.so.2 (0x00007f338bd9f000)
    libIlmImf.so.6 => /usr/lib/libIlmImf.so.6 (0x00007f338bade000)
    libHalf.so.6 => /usr/lib/libHalf.so.6 (0x00007f338b89b000)
    libIex.so.6 => /usr/lib/libIex.so.6 (0x00007f338b67b000)
    libraw.so.5 => /usr/lib/libraw.so.5 (0x00007f338b3eb000)
    libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f338b1dc000)
    libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f338afd8000)
    libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f338add2000)
    liblcms.so.1 => /usr/lib/x86_64-linux-gnu/liblcms.so.1 (0x00007f338ab9a000)
    libImath.so.6 => /usr/lib/libImath.so.6 (0x00007f338a994000)
    libIlmThread.so.6 => /usr/lib/libIlmThread.so.6 (0x00007f338a78d000)
    libjasper.so.1 => /usr/lib/x86_64-linux-gnu/libjasper.so.1 (0x00007f338a535000)
    liblcms2.so.2 => /usr/lib/x86_64-linux-gnu/liblcms2.so.2 (0x00007f338a2e3000)

Regards,

David Sanz Krbis.
