### ISSUE TITLE
Can't figure out how to make it work

### ISSUE THREAD

**Issue by verogeorl** [dasaki/ofxKinectBlobTracker#2]
Hello !

I've not coded for a while and I wanted to track feets on the floor using the kinect v2 sensor. I thought of blob tracking to do so. I'm using Visual Studio 2015 on my windows 10 PC. I've never used Linux nor Mac to code so I am a bit confused. Does your code work on Windows?

Best regards,

**Comment by dasaki** [comment]
Hi,

This code is for generic blob detection / tracking. It has been tested with a Kinect 1 only. I suggest you to get advantage of the well documented Kinect 2 user/skeleton detection API, that should let you track the skeleton (including the feet) easily.

Regards,

D.

**Comment by verogeorl** [comment]
How did you make it work? I'm not familiar with the extansion used in the example. 

Thank you for your reply.

Best regards,

**Comment by dasaki** [comment]
Hmmm... too long story. First get familiar to [openframeworks.cc](url) and Qt Creator [www.qt.io/ide](url)

Regards

**Comment by dasaki** [comment]
Sorry, the example is for an older version of openframeworks, it is a code::blocks project [www.codeblocks.org](url)
