### ISSUE TITLE
No Viable conversion Error

### ISSUE THREAD

**Issue by marisadi** [dasaki/ofxKinectBlobTracker#3]
Hi I've just downloaded and am trying out the example code to use with my Kinect v1 and I'm getting this error:
No viable conversion from 'ofShortPixels' (aka 'ofPixels_<unsigned short>') to 'float *'
It occurs on line 250 of ofxKinectBlobFinder.cpp
`float * distance = kinectPtr->getRawDepthPixels();`

Any ideas?

Thanks

**Comment by dasaki** [comment]
Please let me know if this works:
change
`float * distance = kinectPtr->getRawDepthPixels();`
for
`float * distance = kinectPtr->getDistancePixels();`

**Comment by marisadi** [comment]
Hey, thanks for the fast response!

I made the changed and I still get the error:

No viable conversion from 'ofFloatPixels' (aka 'ofPixels_<float>') to 'float *'

**Comment by dasaki** [comment]
Did you use `getDistancePixels` or `getDistancePixelsRef` ?

**Comment by marisadi** [comment]
`getDistancePixels`

**Comment by dasaki** [comment]
If you are using this library: [https://github.com/ofTheo/ofxKinect](https://github.com/ofTheo/ofxKinect)
Did you change this in ofxKinectBlobFinder.h ?

`#include "ofxKinectV2.h"`

for 

`#include "ofxKinect.h"`

**Comment by dasaki** [comment]
I have just updated the code and example in github to work with current oF release.
